
on: [push, pull_request]

name: Jsonpath CI

jobs:
  check:
    name: Jsonpath Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Check (no features)
        uses: actions-rs/cargo@v1
        with:
          command: check --no-default-features

      - name: Check (all features)
        uses: actions-rs/cargo@v1
        with:
          command: check --all-features

  lints:
    name: Jsonpath Lints
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run clippy (no features)
        uses: actions-rs/cargo@v1
        with:
          command: clippy --no-default-features

      - name: Run clippy (all features)
        uses: actions-rs/cargo@v1
        with:
          command: clippy --all-features

  test:
    name: Jsonpath Tests
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Run tests (no features)
        uses: actions-rs/cargo@v1
        with:
          command: test --no-defeault-features

      - name: Run tests (no features)
        uses: actions-rs/cargo@v1
        with:
          command: test --all-features
